# Generated by Django 3.0.5 on 2021-06-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='key',
            field=models.CharField(max_length=50),
        ),
    ]
